### ISSUE TITLE
Expose error functions in kadm

### ISSUE THREAD

**Issue by turkenh** [twmb/franz-go#104]
Currently [error functions in kadm](https://github.com/twmb/franz-go/blob/9a07b598f8fa6148589841450558194ad26c6f22/pkg/kadm/errors.go#L12) are `private`. 

Having them as `public` would help consumers of this library to check the returned error.

**Comment by twmb** [comment]
Do they need to be separate errors? This could be one type, `MissingError`, and if partition is -1 it was not set. What do you think?

**Comment by twmb** [comment]
That type is a meta error meant to wrap all errors within responses that Kafka could return. I don't think it makes much sense here because the errors in `kadm` are unique and, more importantly, I'm not sure it makes sense to roll all those errors into one error (that'd be just as good as an `error` itself).

**Comment by twmb** [comment]
Perhaps maybe you mean that this should return kerr.UnknownTopicOrPartition?

**Comment by twmb** [comment]
Closed with https://github.com/twmb/franz-go/commit/6ab90446136a9580499ecc3c242815e8613eb87b
