### ISSUE TITLE
Does groupConsumer callback upper layer at generation cleanup phase?

### ISSUE THREAD

**Issue by yuzhichang** [twmb/franz-go#105]
Upper layer registers sarama `ConsumerGroupHandler.Cleanup` callback to ensure done handle received records before rejoin. This helps to avoid consuming duplicated record at the next generation.
Does franz-go have such feature?

**Comment by twmb** [comment]
The "cleanup" corresponds to the Java client's `onPartitionsRevoked`. This client provides the same concept: `OnPartitionsRevoked`. It is a bit more difficult to use because you have to hook it into your client properly.

`OnPartitionsRevoked` blocks a new group joining until the function finishes. This does mean you need to be careful not to exceed the rebalance interval. There's more docs on the options themselves, let me know if you have any more questions!
