### ISSUE TITLE
Offset management behaviour

### ISSUE THREAD

**Issue by vladimirkadic-ts** [twmb/franz-go#118]
Hi,
I'm trying out franz-go for communication with confluent.cloud kafka and I stumbled upon some strange behavior while testing the consumer part. 

I have consumer and producer split as two clients.

I instantiate consumer with kgo option: `kgo.ConsumeResetOffset(kgo.NewOffset().AtEnd())` by the definition in code it looks like it will start reading from the end of the topic, so only newly added messages. For some strange reason, I keep getting old messages as well. 

The test is simple, I: 
- start a producer
- add two records: r1, r2
- sleep for 15 seconds
- start a consumer
- produce one more message r3
- consume the message(s) with `PollFetches`

Expected result: r3
Actual result: r1, r2, r3

^ This part actually works once or twice on multiple runs, but in most cases, it doesn't.

I get the same issue when I try using the reset offset option with `Relative`, eg:
- add 5 records (r1, r2, r3, r4, r5)
- start consumer with `kgo.ConsumeResetOffset(kgo.NewOffset().Relative(-2))`
- consume the messages

Expected: r4, r5
Actual: r1, r2, r3, r4, r5

By looking at the comments in code, Relative should work as I described, no? 🤔 

Consumer options:
- consume topics
- consumer group
- consume offset reset
And some standard options like logger, metrics, sasl..

I'm using go: 1.16
Library version: v1.2.6

Could this be something related to the library or some Kafka configuration option I'm unaware of?

And another question, is it possible to find the offsets at the given timestamp and tell the consumer to start from those offsets onward? 🤔  or if the library has an abstraction for this where you just supply a timestamp

Thanks in advance

**Comment by twmb** [comment]
Are you using a consumer group or no?

w.r.t. offsets @ a timestamp, check https://pkg.go.dev/github.com/twmb/franz-go/pkg/kadm#Client.ListOffsetsAfterMilli. Technically the package is not stable, but it's not likely that this API will change. It's currently a separate module to allow me the freedom to change some aspects if necessary.

**Comment by vladimirkadic-ts** [comment]
Yes, I'm using a consumer group. 

And thanks for the `kadm` link, will check this out! 🙇🏼

**Comment by twmb** [comment]
What's the remote Kafka version? >= 2.3?

My suspicion is that this is defaulting internally to exact offset resetting. I'm not 100% sure if that's that case and if so, why. Could you possible grab debug logs (to see which requests are being issued, potentially with the kgo.BasicLogger)?

I can look more into this tomorrow.

**Comment by vladimirkadic-ts** [comment]
Sorry for not updating this yesterday, version of Kafka is supposedly 3.0.* (as confluent.cloud is running the latest version), unfortunately, It seems there is no way for me to visually confirm this. 

As for the logs, these are the log details from the basic logger (from the test explained above, both producing and consuming): https://privatebin.net/?2c8ab46eb63b6d2f#GGxVGNukbkYtK6xCrEowu669EtwzNNDPzNYUuNgftw1y

**Comment by twmb** [comment]
I spent some time looking into this, I'm curious what your behavior was for testing this. There may be a few factors at play that I'd like to rule out.

- Are you using autocommitting?

If so, were you exiting relatively quickly after consuming? It's possible that a commit did not go through (since we only allow the prior records to be committed _at_ the next poll, and we do not autocommit on shutdown).

- How many partitions does the topic have?

In the relative example, if the topic has more than one partition, then the relative aspect is to each _partition_, not to the total ordering by time of all messages. If I create a topic with two partitions, I could get four records, vs. if I create with one partition I'd get two records.

- How does the code look in the first example of sleeping and producing and consuming?

I've tried to recreate the scenario a bit and I'm not seeing this. I'm wondering how much of this is dependent on timing, and Kafka choosing to balance a group at a certain time.

---

I remember taking a look at the logs (they're expired now) and seeing OffsetForLeaderEpoch, which should only be issued an existing group (because only committed offsets have leader epochs). If I could see the code to setup the scenario, I may be able to suss out what the problem is -- right now I'm not entirely seeing it.

**Comment by vladimirkadic-ts** [comment]
Hey hey, I'm sorry I missed the last message.

No, I'm not using auto-committing, committing is done in batches after the records have been properly processed. It's a long-running process that will halt only in case of some extreme cases, so this shouldn't be an issue. 

The topic has two partitions.

Regarding the code, I'll send that in a bit (a day or two if it's not a problem).

> edit: also sorry for the delay, I decided to not think for about two weeks.
^ Not a problem :-)

**Comment by twmb** [comment]
Perhaps some of what you're seeing may be related to the topic having two partitions -- consuming two from the end could consume two records from each partition. However, the first message indicates that 5 were consumed, so perhaps another thing is up here (maybe the same-group-across-restarts thing?).

**Comment by twmb** [comment]
Hey there -- pinging on what you think of the above^ and if you're able to have a code sample (or anything I can do to trigger this locally)!

**Comment by vladimirkadic-ts** [comment]
Hey @twmb, 
I'm really sorry for missing replies, a bit slammed so I didn't have time to build the example. Regarding "(maybe the same-group-across-restarts thing?)." I will have to dig it up a bit 🤔 

I will close this issue, for now, no point in waiting for me, I'll dig a bit deeper when I'm free a bit, and if I find something I'll reopen. 

Thank you for your help

**Comment by twmb** [comment]
Ah no worries! If you ever have time to look into this please let me know! :) And thanks!
