### ISSUE TITLE
reuse single connection to publish/subscribe at any time

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#121]
does it possible to improve this package by adding this stuff
1. create some Conn to kafka broker
2. at any time when i'm want to publish i'm create NewProducer(c Conn, opts...) and do  Produce/ProduceSync 
3. at any time when i'm want to subscribe to topic i'm create NewConsumer(c Conn, opts...) and use it

why i want this - my use case to have in my framework kafka broker, user at any time can call subscribe to any topic, now i need to create separate client for each subscriber, if you create helper stuff i can effectively reuse the single client to receive them all.

**Comment by twmb** [comment]
So if I'm reading this properly -- the thought is that you want to reuse the underlying connections between brokers? Will the connection be used in both clients at the same time, or will there be some separation between using the clients?

**Comment by vtolstov** [comment]
i'm prefer to use single conn with all clients, as kafka can send records for many topics in single batch, also it supports as i understand publish to multiple topics (dont know how this works, does kafka client needs to combine batch with messages only to single topic or one batch may contain messages for multiple topics)

**Comment by twmb** [comment]
The batching for producing occurs within a single client already; reusing a connection can't help batching. The client internally batches all topics / partitions into a single produce request.

Reusing connections _may_ be beneficial if you're using the clients at separate times. But, it wouldn't be sound to allow two clients to use the same connection at the same time, because there may be writer & reader synchronization issues. AFAICT the only way to use a single connection in two clients is to lock the connection around an entire request write and response read. Locking around the response read would not be so good, because Kafka replies to requests in order, but the clients do not know which order they wrote the request, so all clients would need to peek at the first bytes on the wire to see if the response coming back is the response they're looking for (if not, it may be for another client). This is actually what segment's kafka-go client does, which is part of what makes the concurrency aspect of connections a bit odd: https://github.com/segmentio/kafka-go/blob/d5d9116c820e66943605e2c599cceae11e9bb5c1/conn.go#L1335-L1371.

So, I'm not sure a pool to reuse connections in two _active_ clients at the same time is sound.

What I would like to do, though, is reuse the same connection between two clients when one client dies and then the other client starts being used. This would speed up connection initialization (so long as both clients use the same sasl).

**Comment by twmb** [comment]
I've evaluated this a bit (and wrote a chunk of code for it). I'm not sure this is feasible at the moment. I think this issue can be reopened if a suitable API can be found. There are a few problems:

* we would need a connection pool that we only put back into once all requests on a connection are fully read / resolved
* the API needs to take account of connection throttling (this is the bigger problem). We could sleep before putting a connection back into the pool, but the bigger problem is if we put a busy conn back into the pool and then it's suddenly used for something important and is immediately throttled.

The second point could potentially be addressed by having a different pool per connection type (produce, fetch). But, I haven't found an API that I'm happy with to address the throttling problem. I was planning to add something if throttling wasn't taken into account, but throttling really makes any aspect of connection pooling a bit sketchier.

Perhaps an API could just ignore throttling: put back into pool only after any throttling is obeyed, not care if we use a connection that is about to be throttled. Maybe most people don't throttle connections (I'd guess this to be true), so the throttling concern is overblown. But, it's worth nailing down how this should look before continuing.

This request is also related to a similar sort of ask about having many concurrent admin requests, but that API is also undefined.

Closing for now, but if a better API is thought of or if this comes up again separately, we can reopen.

**Comment by vtolstov** [comment]
I don't have better ideas, so for now I think that you are right.
Maybe if i have problems with connection count i can re-subscribe to all needed topic with new client and close older with some locking protection in my high level code in framework
