### ISSUE TITLE
Committing with group consuming

### ISSUE THREAD

**Issue by clocklear** [twmb/franz-go#128]
Hi @twmb !  This isn't explicitly a problem with your package, but we've encountered an issue in our usage that I would greatly appreciate your thoughts on.  Consider the following:

We use `franz-go` in one of our applications to consume from Kafka and delegate those records to higher-order record handlers.  We've enabled the `AutoCommitMarks()` option for the client so that we can have some basic control over when a particular record for that consumer group is check-pointed in Kafka (because our handlers may succeed/fail/timeout/retry, etc).  Ideally we would not mark a particular record as processed until the higher-order handler indicates it is finished.  For performance reasons, our code is structured such that there is a high amount of concurrency associated with 'processing records'. We poll fetches, check for errors, and then use `.EachRecord()` to invoke some number of concurrently processed handler funcs, which is limited to some number.. say, 500.  This works as expected, and works well.

However, because we are doing concurrent processing of records, it seems like it may be possible to 'process' records with higher offsets for a particular partition before processing lower-numbers records in the same partition.  For instance, processing of record 77 may complete before processing of record 50.  Or even 50 may fail while 77 succeeds.  During the autocommit phase of the client, what will happen in this scenario?  Does the franz-go package handle this scenario in any way?  Do you have any thoughts on how we might perform this differently such that we are eliminating data loss?  We believe that in certain edge-cases currently the consumer code is check-pointing the offset 77 and then the service is terminating (for unrelated reasons), which causes consumer B to pick up the partition and learn that it should start from offset 77 (and record 50 never gets reprocessed).

Does that make sense?  Thanks for your time!

**Comment by twmb** [comment]
> During the autocommit phase of the client, what will happen?

If using `AutoCommitMarkers`, the code _currently_ prevents rewinds. I'm thinking to allow rewinds given some recent thought in #125, and because CommitRecords currently allows rewinds. So in this scenario: if you mark 77 and then 50, the code will commit 77. Soon, the code may commit 77 and then allow your second mark of 50 to rewind and commit to 50.

> Do you have any thoughts on how we might perform this differently such that we are eliminating data loss?

If a single partition is processed out of order such that individual records can fail to be processed while other later ones are successful, and you commit the successful ones, and then your program crashes before you can "rewind" to the earlier failed commit, you will experience data loss. If you do rewind, then you'll experience duplicate processing.

To more reliably avoid data loss, you'd need to switch the concurrency to be per-partition rather than per record, and always process & commit partitions in record order. Alternatively, if duplicate processing is ok, on your side you could have a second worker queue that only commits records in order, regardless of whether they finish out of order:

```go
        var nextCommitOffset int64
        var rs []*kgo.Record
        for {
                r := <-done // done == chan(*kgo.Record), per partition
                rs = append(rs, r)
                for len(rs) > 0 && rs[0].Offset == nextCommitOffset {
                        cl.MarkCommitRecords(rs[0])
                        nextCommitOffset++
                }
        }
```

that^ loop would need to be done per partition (I haven't tested nor compiled that, either), but some smarter code could be devised to allocate less, use one loop rather than one per partition, etc.

**Comment by clocklear** [comment]
Thanks for the feedback.  In our case, duplicate processing is far more tolerable than data loss, so we will investigate something along these lines.
