### ISSUE TITLE
Is it possible to specify the concurrency level of produce requests with idempotent disabled?

### ISSUE THREAD

**Issue by beanliu** [twmb/franz-go#129]

**Comment by twmb** [comment]
Not currently, what's the use case for this? I had this as an option for a brief period of time, but I removed the option before a minor release.

This is the commit that introduced the option: 229f9da2906dce9813c4ad9d93385712fd95bd01
This is the commit that removed the option: d1ba10360f457b4007cb2910bc23fc37a07b05cd

**Comment by beanliu** [comment]
This is for cases that require high throughput and can tolerate data duplication/loss to some extend.

But seems that higher level of producer concurrency (than default 1) is not very useful according to the comment of your commit (https://github.com/twmb/franz-go/commit/d1ba10360f457b4007cb2910bc23fc37a07b05cd), could you elaborate on that? It's a bit counterintuitive TBH.

**Comment by twmb** [comment]
More than 1 can be beneficial, but more than 5 likely isn't, so the thought I have here is you might as well enable idempotency while reaping the benefit of 5 concurrent requests.

Note Jay Kreps's comment in this thread (his first comment): https://issues.apache.org/jira/browse/KAFKA-5494,
as well as the max.in.flight analysis in this wiki page: https://cwiki.apache.org/confluence/display/KAFKA/An+analysis+of+the+impact+of+max.in.flight.requests.per.connection+and+acks+on+Producer+performance

The main takeaway is that more than 2 in flight may actually not be too beneficial, but part of me wonders if that's due to inefficiencies within the Java implementation. This Go client actually limits at 4 in flight due with idempotency to a race around the upgrading from 1 to "5", but I could do some things to make it 5 as well.

What do you think about the above analysis & issue discussion? Is it still worth adding an option to allow more than 1 for non-idempotent production? (I'm somewhat hoping to push everything towards idempotency)

**Comment by beanliu** [comment]
The analysis seems solid. Thanks for the detailed explanation 👍 

I think it makes sense to enable idempotency by default if it's a strict win in terms of performance (assume performance overhead of the cluster is trivial here).

Minor suggestions:
- Update doc/comment of `DisableIdempotentWrite` to reflect the performance implications.
- Update default concurrency level to 2 when idempotent disabled to increase throughput.

**Comment by twmb** [comment]
Idempotency isn't necessarily a strict win in terms of performance, but there is no loss. Kafka 3.0 is enabling idempotency by default as well: https://cwiki.apache.org/confluence/display/KAFKA/KIP-679%3A+Producer+will+enable+the+strongest+delivery+guarantee+by+default

I can update the doc on `DisableIdempotentWrite`, however I'm not sure about defaulting to 2 when idempotency is disabled -- this may result in more out of order records than people expect.

**Comment by beanliu** [comment]
> this may result in more out of order records than people expect.

You are right. Then maybe it's better to leave the options to the users? Since they should know what they are doing (different tradeoffs in different scenarios) if they decide to stay away from the default configuration.

**Comment by twmb** [comment]
Reintroduced here https://github.com/twmb/franz-go/commit/cd53e97174e9a9d82f2832019935921d19ac8d8d
with a more tedious name and more docs indicating it shouldn't really be used,

this will be in v1.4.

**Comment by twmb** [comment]
Sorry about the delay -- v1.4 _should be_ this week. I think there's _one_ more thing to add to it. I'll reopen this for now so that it can be properly closed when v1.4 is released (now that I have a v1.4 tracking issue).

**Comment by twmb** [comment]
The option now exists in v1.4
