### ISSUE TITLE
Question: How is the consumer config setting max.poll.interval.ms implement and used in franz-go?

### ISSUE THREAD

**Issue by brunsgaard** [twmb/franz-go#140]
In the code I can not find any references to `max.poll.interval.ms`([link](https://kafka.apache.org/documentation/#consumerconfigs_max.poll.interval.ms)).

Does franz-go have behaviour that will trigger a rebalance if a poll has not been issued for a period of time? It is not a feature I am missing, just curious on how this works in this client.

**Comment by twmb** [comment]
I didn't know of that config knob (I implemented most of the client from KIPs), so it doesn't exist. It could, but I'm a bit unsure about the need -- it seems like a user may want to auto-fail the group member if it is inactive (gets stuck) for a period of time, but that also increases risk of the group member coming back alive and then the group doubly processing records.

Inside the client right now, the group heartbeats always, and rebalance is triggered in the normal ways: leader detects new partitions, or member detects new topics, or some member times out, or new member joins.

Is there a need for this option? I'm currently erring on this behavior is something that is more suited to an application using the client rather than within the client.

**Comment by brunsgaard** [comment]
> Is there a need for this option

Not in my opinion, at least I dont see the need right now. Thanks for your answer. If others bring it up, lets reevaluate but for now I will close is issue/question. I was just curious.
