### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by victor-oancea-leftclick-io** [twmb/franz-go#149]
Building any project that uses this, results in a compilation failure:
`../../../go/pkg/mod/github.com/twmb/franz-go@v1.4.0/pkg/kgo/client.go:1218:14: undefined: kmsg.AlterISRResponse`

**Comment by victor-oancea-leftclick-io** [comment]
its cuz of https://github.com/twmb/franz-go/commit/845bc50e6da0334a904a4f3ddef7f61d7535c93d


@twmb you forgot to regenerate files

**Comment by twmb** [comment]
This is because kmsg is currently a package without a stable version. I'm going to tag kmsg as v1.0 because of this.

I'm assuming you ran into this due to `go get -u ./...`, which bumped kmsg to the latest version, which then broke kgo because kgo can't depend on any specific kmsg version because kmsg is unversioned. You can fix this in the meantime with `go get github.com/twmb/franz-go/pkg/kmsg@v0.0.0-20220310045829-806cf534caf0`.

I'll close this issue when I bump v1.4.1 depending on kmsg 1.0.

**Comment by twmb** [comment]
I've released v1.4.1 and tagged kmsg to v1.0.0, meaning this should not happen again.
