### ISSUE TITLE
Add ability to set a MaxVersion when forming a request

### ISSUE THREAD

**Issue by rmb938** [twmb/franz-go#153]
When making a `kmsg.Request` by hand for example `SyncGroupRequest` it would be nice to be able to specify a custom MaxVersion that will override the hard coded max version in the messages.

Certain requests (`SyncGroupRequest` has been the only one I've found so far) when made by hand for older versions cause Kafka to return an error because Franz always upgrades the version to the MaxVersion.

i.e If I send a `SyncGroupRequest` that doesn't have `ProtocolType` and `Protocol` set (version 4 or bellow) franz auto upgrades it to version 5, sends them to Kafka as nil. This is causes Kafka to return InconsistentGroupProtocol (err 23).

My usecase for this is probably very specific to what I'm building so I completely understand if you don't want to add something like this.

**Comment by weeco** [comment]
That's already available, just set it in the options when you create the client.

```go
	return []kgo.Opt{
		kgo.SeedBrokers(seeds...),

		// SASL Options
		kgo.SASL(scram.Auth{
			User: user,
			Pass: pass,
		}.AsSha256Mechanism()),

		kgo.MaxVersions(kversion.V2_4_0()),

		// Configure TLS. Uses SystemCertPool for RootCAs by default.
		kgo.Dialer(tlsDialer.DialContext),
	}
```

**Comment by twmb** [comment]
Interesting, so you have a use case to send v4 of a request, and then v5 when using the same client?

**Comment by rmb938** [comment]
Yep, I'm using this client to create a proxy in essence so I need the ability to flip versions on a request by request basis. 

My setup is Kafka Clients -> My Proxy -> backend kafka clusters. Kinda like an Nginx but Kafka protocol aware where there's multiple kafka cluster backends and the proxy smartly distributes requests based on what that client is making. Inspired by this blog post https://www.confluent.io/blog/tencent-kafka-process-10-trillion-messages-per-day/ as the software mentioned there was never open sourced so I thought to give it a shot.

Most requests don't seem to care about having the version match exactly and proxy through fine to the backend kafka cluster but the SyncGroupRequest is being extra picky due to the extra fields being sent in v5. I believe this is due to how consumer groups determine which protocol to use for the group and SyncGroup v5 changes that up slightly.

I currently got around this issue by coping the generated code and removing the version 5+ bits and setting the max version to 4. Then I just use that one to send v4 messages and everything works fine.

**Comment by twmb** [comment]
Perhaps this could be done with a different option, `kgo.ExactVersions` (or maybe a different name) that obeys the version in the field of the request and never overrides it.

I'm currently wondering how much to include for an eventual v1.5, and I'm not sure I'd want to cut a v1.5 with this option alone, so I'm not sure on the exact timeline of any new option offhand.

**Comment by rmb938** [comment]
Oh I like that idea.

Yup I agree just changing 1 thing is probably not enough for a 1.5 release. I do have a work-around for now so I'm not too concerned about needing timelines or anything. If I have any more idea for what to include in 1.5 I'll let you know!

**Comment by parsa20001999** [comment]
> When making a `kmsg.Request` by hand for example `SyncGroupRequest` it would be nice to be able to specify a custom MaxVersion that will override the hard coded max version in the messages.
> 
> Certain requests (`SyncGroupRequest` has been the only one I've found so far) when made by hand for older versions cause Kafka to return an error because Franz always upgrades the version to the MaxVersion.
> 
> i.e If I send a `SyncGroupRequest` that doesn't have `ProtocolType` and `Protocol` set (version 4 or bellow) franz auto upgrades it to version 5, sends them to Kafka as nil. This is causes Kafka to return InconsistentGroupProtocol (err 23).
> 
> My usecase for this is probably very specific to what I'm building so I completely understand if you don't want to add something like this.

**Comment by twmb** [comment]
Actually, I think this can be done without any new APIs in this library: you can have a helper type that explicitly overrides `SetVersion` to be a no-op:

```go

type ExactVersionRequest struct{ kmsg.Request }

func (ExactVersionRequest) SetVersion(int16) {}
```
and whenever you want to disable any version setting from kgo, wrap your request in `ExactVersionRequest`.

I've realized that `kgo.ExactVersions` doesn't exactly work within kgo itself, because if you issue any group request, kgo issues a `FindCoordinator` request to learn which broker to issue your group request to. If `ExactVersions` were used, then `FindCoordinator` would be bound to 0. v0 doesn't allow looking up transactional requests. As well, the client internally issues metadata request sometimes (learn of the coordinator, learn where to split topics); this would bound those requests to v0 as well. For the most part, v0 for metadata works, but no reason to avoid going higher.

I was then going to some exact version optional interface to kmsg, and have it auto implemented by all requests there, and this method would disable SetVersion ... and then I realized, why not just use a wrapper?

I think this small wrapper is better left to external libraries, but lmk if you think this should be added in kmsg or if this wrapper doesn't work for you. For now, I'll close the issue, but again feel free to open.

**Comment by rmb938** [comment]
Yea but that's for the life of the client. I would like to be able to
customize it for each request without needing to make a new client.

**Comment by twmb** [comment]
Isn't the above suggested specific for each request? `SetVersion` ignores the version being set, so the version in the kmsg.Request as specified by you pins the exact version to be used.

It's very coincidental that you messaged on this comment, I was thinking to add a new `PinVersion` API for #214 but revisiting this thread because of the ping, I think the `ExactVersionRequest` idea above is even easier.

**Comment by rmb938** [comment]
Err that's weird... I totally did not comment that 7 hours ago and it said it was sent via email... which I didn't send O.o

Changing passwords...

**Comment by rmb938** [comment]
Actually scanning through my email. This looks like a github bug. I sent an email comment with that exact contents back in March 27th, it never went through so I made https://github.com/twmb/franz-go/issues/153#issuecomment-1080831278 in the UI. Looks like now it finally went through haha.

Anyway, I did end up using `kgo.ExactVersions` but if you are working on a better solution `ExactVersionRequest` seems like a good one.
