### ISSUE TITLE
Add Proxy option/documentation

### ISSUE THREAD

**Issue by Herrmlo** [twmb/franz-go#155]
During configuration I was hoping to see a `WithProxy(...)` function or something similar.
In the case that this is a quite trivial configuration I'd be happy if instead an example could be included, because I'm quite frankly struggling to implement it.

**Comment by twmb** [comment]
What would the proxy be used for? I'm wondering if it's possible to provide a custom dialer -- if this can't be provided with a custom dialer, what does a `WithProxy` API look like?

**Comment by brunsgaard** [comment]
Hi, you can not really proxy Kafka easily due to the way broker discovery works. There are some options but it can not be done in the client, you need a Kafka aware/intelligent proxy

https://github.com/grepplabs/kafka-proxy

https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/kafka_mesh_filter

Are solutions I know of.

**Comment by Herrmlo** [comment]
Hi, my approach was indeed wrong. Kafka-proxy certainly looks like what I'll need to be going for. Thanks to both of you.

**Comment by twmb** [comment]
Awesome, good to hear.
