### ISSUE TITLE
Log levels and errors

### ISSUE THREAD

**Issue by ekeric13** [twmb/franz-go#172]
Some of the log levels are a bit noisy for my use cases. Specifically logs that occur on a pre-determined frequent basis. Like I was wondering if I could make "autocommitting" a trace level log:
https://github.com/twmb/franz-go/blob/7b565d03acb18efad59ef7f5fa789cb3859865f3/pkg/kgo/consumer_group.go#L1930

And the communication between the broker:
https://github.com/twmb/franz-go/blob/7b565d03acb18efad59ef7f5fa789cb3859865f3/pkg/kgo/broker.go#L969
https://github.com/twmb/franz-go/blob/7b565d03acb18efad59ef7f5fa789cb3859865f3/pkg/kgo/broker.go#L1166

As those all happen on a regular basis. It would be nice if I can just turn these into trace level logs but i don't see a way without changing the code. And I find some of the other debug logs very useful.

Also one thing that i find confusing is in my communication I see I have the error: `"err":"\u003cnil\u003e`. But these logs don't surface for error level logs or info level logs. Just debug level logs. Furthermore that error seems to translate to `<nil>` so I don't have context around what it means.

**Comment by twmb** [comment]
It's not recommended to run the logger at debug level, that's really for if you're having problems / there's a bug you're running into that needs deep investigation. I've tried to tune the logs emitted over time, but the current debug logs largely exist due to them being very useful debugging bugs I've had in the past. I'd recommend to log at info level at most.

Re: `<nil>`, this is just say there is no error. It's easier to emit `<nil>` for an error (i.e. the error value) rather than conditionally adding the field in every log message.

What is the use case for logging at debug level?

**Comment by ekeric13** [comment]
Just trying out franz-go for the first time :) Usually like to run my services in debug level for a few weeks before going to info.

**Comment by twmb** [comment]
yeah it's hard to know what should be separated into trace vs. debug, that's a bit like guessing "which logs will _really_ be relevant for my bug?" and in my prior fixes to this library ... they all come into play at some point :)
