### ISSUE TITLE
[QUESTION] Why is not possible disable ConnIdleTimeout?

### ISSUE THREAD

**Issue by robsonpeixoto** [twmb/franz-go#202]
In some system the produce time can be very critical, but the idle connections are being closed requiring more time(TLS handshake + authentication) to produce on Kafka.

Maybe allow reduce the `conn min idle timeout` to `0` will help on it.

**Comment by ssorren** [comment]
How is your broker configured, specifically "connections.max.idle.ms"? No matter what you're client is set to, you may still be shit down by the broker itself. On the client side, you should be able to control this with `kgo.Dialer` client option

**Comment by twmb** [comment]
@robsonpeixoto as indicated by @ssorren, the connection can be closed by the broker, or the connection could be dead for some other reason. Because of how this client works (it does not continuously read the connection), a dead connection actually cannot be noticed until a write occurs. The idle timeout enables an independent loop in the client that periodically reaps connections that have not been written to / read from in a certain period of time. If this loop is disabled (idle timeout == 0), then there would be more errors (and then retries) in the event of dead connections.

What's the use case for wanting a connection to be open but idle for a long period of time? The max idle timeout is 15 minutes. Idle connections take resources on the broker (minimal, but some memory), likely have a small window size anyway, and may die unexpectedly.

**Comment by twmb** [comment]
@robsonpeixoto ping on the above^. I could allow 0 to disable, with the caveat this increases risk of failed requests.

**Comment by twmb** [comment]
I'm going to close this issue -- if you want to keep a very long timeout, you can use something like 24hr or so (or, years). Another issue I remember now (and the reason I actually introduced this) is that _without_ idle connection reaping, connections can sit in an `CLOSE_WAIT` state in the kernel, and if your traffic is _very_ infrequent (bordering on never again), the connections hang in a zombie state.

**Comment by robsonpeixoto** [comment]
Thanks @twmb and @ssorren. My broker is configured to close idle connections in 10 minutes of inactivity. I'll increase the max idle timeout to 9 minutes.
