### ISSUE TITLE
Block poll if no commit

### ISSUE THREAD

**Issue by ice-ares** [twmb/franz-go#234]
Hey @twmb ,

I was wondering if there is any way to block polling (or reprocess the same offset over and over again) until a commit is issued.
Similar with `MarkCommitRecords` and `AutoCommitMarks` but with forcing the client to not get new offsets until the current offset is committed.

**Comment by twmb** [comment]
What's the purpose / intent for this

**Comment by ice-ares** [comment]
If we have a downside for a few hours( IE database is down or some servers/services we call while processing records fail) we dont advance with the offset until everything is back up and running

**Comment by twmb** [comment]
There are a few offsets that each advance:

* The offset fetched is advanced when the previous fetch is unbuffered -- i.e., when you poll. If the poll returns offsets 6 through 8, then after you poll, a fetch is issued for offset 8.
* The uncommitted offset is advanced when records are returned from being polled. If a poll returns 6 through 8, then the uncommitted offset internally will be 8
* The committed offset is advanced depending on your options: for autocommit, committed is advanced to the _previous_ poll once things are committed. For marks, the committed offset is advanced after the commit is successful. For manual committing, the committed offset is advanced when you commit yourself.

If your database is down while records are processing, then the client isn't continually advancing offsets internally _so long_ as you aren't continuously polling.

Which offsets are you seeing advance that you would like not to?

**Comment by twmb** [comment]
Having the option to poll the same records means that the client would have to change to _not_ pre-fetching the next batch of data, and instead it would only fetch the next batch when you tell the client to advance. This would be quite bad for latency.

The easier implementation of this idea would be to just not return new data until the client is told to advance, so, rather than repeatedly returning the same data, it'd just return nothing.

However, I think another option as the user is to not poll until you are ready to advance. In your scenario, rather than polling 10 times while the first commit is failing, you could poll 1 time and wait for failure or success. And then, since you're controlling when to poll, you can keep the first poll in your application to repeatedly try inserting into the database until there is success.

I also suspect that with an option to repeatedly return the same data, it'd be very easy to make a mistake somewhere as a consumer of the data and accidentally process duplicates. What if you poll six times, have six copies of the data, and then the second copy is suddenly successful? How do you know to drop copies three through six, how do you differentiate that from the now _new_ data from the 7th poll?

Without knowing more about the current problem, it seems that the proposal here could potentially be better addressed by changing certain areas of the application itself -- it may be more resilient within the application, and it allows usage of the kgo client to be easier to reason about.

**Comment by twmb** [comment]
one fetch per broker can be buffered
MaxConcurrentFetches can limit this
