### ISSUE TITLE
question about failures I'm seeing with ProduceSync 

### ISSUE THREAD

**Issue by dbudworth** [twmb/franz-go#238]
I was seeing a couple odd behaviors today while kicking the tires on your package (which seems pretty darn nifty so far)
I don't believe these are bugs, this is more questions about things I saw

**First**: random UNKNOWN_SERVER_ERROR errors  after several thousand sends 
the kafka broker didn't seem to log anything

I totally believe my kafka server returned something wonky, but the issue is that it's hard to troubleshoot as the error doesn't contain the actual code returned by the broker.   so you're kinda stuck.  Curious how you normally troubleshoot that stuff

**Second**: compression kicking in after exactly 100,000 messages
my kafka instance doesn't seem to support snappy for some reason.  It logs:
`org.apache.kafka.common.KafkaException: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy`
(and a stack)

that's not the weird part.... The weird part is that this error happens on exactly the 100,000th message every time.  
grepping through the code, `100000` doesn't show up 

explicitly setting no compression makes this problem go away, but I don't really get why the first 99,999 messages don't fail

For the first error, I haven't seen it in a while, it's entirely possible that these two things are the same issue and I just didn't notice the stack on kafka.  (unlikely, as I was looking for the stack, but possible)
I also wasn't logging send count at that time, maybe it was on the 100,000th record as well

another thing of note, the first error I got was while sending every 10ms in a loop.  I got it several times but it didn't seem consistent as to when

for the second (the snappy exception), i was sending in a tight loop with no delay

in both cases, i get UNKNOWN_SERVER_ERROR.  
So, if failed compression selection is a detectable thingie, maybe there is a bug around improper error return

any thoughts around these two issues?

relevant code:
```
res := cli.ProduceSync(ctx, &kgo.Record{
	Key:       []byte(cmd.Id),
	Value:     bs,
	Topic:     topic,
	})
if err := res.FirstErr(); err != nil {
	if errors.Is(err, context.Canceled) {
		return
	}
	panic(err) // panics with UNKNOWN_SERVER_ERROR
}
```

**Comment by twmb** [comment]
> it's hard to troubleshoot as the error doesn't contain the actual code returned by the broker

Unfortunately, this is the actual code returned by the broker. My errors list [here](https://github.com/twmb/franz-go/blob/master/pkg/kerr/kerr.go#L76-L184) is up to date with the latest set of potential Kafka errors [here](https://kafka.apache.org/protocol#protocol_error_codes).

The broker logs would have more information for _why_ it is sending unknown_server_error, though you might have to enable additional logging.

> kafka instance doesn't seem to support snappy

I wouldn't expect that: snappy has been supported since Kafka 0.8.0. Perhaps this is why unknown_server_error is being returned, because brokers expect this compressor to be available and there is no error code for if it is not.

How are you generating the 100k messages? When you opt into using compression (or use the snappy default), the client compresses the data, _but_ if the compressed data is larger than the non-compressed data, the client instead sends without compression. I'm wondering if something about how you're generating messages causes whatever batch / record at 100k to actually be compressed.

**Comment by dbudworth** [comment]
ahh, neat, I figured (incorrectly) that compression was more an attribute of the session and not an individual message
the thing I'm sending is a proto encoded object with a counter to indicate number of messages sent:
```
cmd.Id = fmt.Sprint("id:", count)
cmd.AccountId = fmt.Sprint("acct:", count)
bs, _ := proto.Marshal(&cmd)
```
(yes, obviously not an optimized test)

changed my app to start at 99,998 and it crashed after 2 messages, when `count == 100000` 
so, it seems like all messages leading up to that didn't warrant adding snappy

now to figure out why my kafka image doesn't support it.  The stack implies it tried to (it knew what class) just that the class was missing.

Thanks for responding, and thanks for building this package!
