### ISSUE TITLE
could not run at go v1.9.0

### ISSUE THREAD

**Issue by zhuby** [twmb/franz-go#241]
when i execute command go mod tidy 
arise error message below:

github.com/twmb/franz-go: module github.com/twmb/franz-go@latest found (v1.9.0), but does not contain package github.com/twmb/franz-go

does it support go v1.9.0?

looking forward for your replying !
many thanks

**Comment by twmb** [comment]
Do you mean Go 1.9, which came out I think 5 years ago and is no longer supported, or do you mean Go 1.19, which came out a few months ago?

This definitely is supported on Go 1.19. Have you followed this section? https://github.com/twmb/franz-go#install

This repo trips up go sometimes because there are a few different modules in the same repo

**Comment by twmb** [comment]
Closing this for now, please let me know if you are still unable to resolve this.
