### ISSUE TITLE
Bug - consumer group offsets are reset under certain conditions

### ISSUE THREAD

**Issue by Zach-Johnson** [twmb/franz-go#247]
Hello! I noticed some strange behavior on the client. I've observed the following:
- A consumer group fails to heartbeat within the session timeout value and is ejected from the consumer group
- The next call the consumer group makes is a CommitRecords request
- This fails since the consumer is no longer part of the group e.g. `broker replied to our OffsetCommitRequest incorrectly! Num topics in request: 1, in reply: 1, we cannot handle this!`
- The client continues with a PollFetch call
- The consumers offsets are reset and it will begin from the start of the topic partitions if the offset reset is "earliest"

I happened to observe this behavior during debugging, so the heartbeats weren't firing. I suspect this _could_ be possible under adverse network conditions though, although I'm not certain and it would be difficult to reproduce. Does this seem like an actual issue or is this expected behavior and just an artifact of abusing the heartbeats with debugger break points?

**Comment by twmb** [comment]
I need to update that log line, it is also printed if there are no `uncommittedOffsets` (internal client concept), and that field is cleared if the consumer is booted from the group. A CommitRecords cannot be successful if the client is booted since well, the consumer isn't in the group. However, you could experience something a bit worse: the client rejoins, does not receive its old partitions back, and commits offsets for partitions now owned by another group member. I recommend looking into BlockRebalanceOnPoll to 100% ensure you don't run into this issue (although you may run into the current issue you're running into more [in fact I wonder if that's why you're running into this issue]).

Are there any commits for the partitions? Resetting to the beginning should only happen if you are consuming and then consuming receives an OffsetOutOfRange error. Otherwise, once the member rejoins the group, it should reset to the last commits for a partition.

**Comment by Zach-Johnson** [comment]
For my current scenario I'm not worried about a rebalance occurring, there is just a single client in the consumer group.

Yes, there are commits for the partitions already, the client is consuming for some time, and then hitting this case. And there is only one client in the group, so it is consuming all the partitions.

**Comment by twmb** [comment]
Is it possible to capture debug logs, or create a reproducer so that I can look into this on my side?

**Comment by twmb** [comment]
Ping^

**Comment by Zach-Johnson** [comment]
Hey sorry! I was trying to reproduce this today, unsuccessfully. I _suspect_ when I was testing this previously I wasn't paying close enough attention to when my app was committing offsets and I was hitting this only when offsets were uncommitted (which makes sense). I will close this, thanks!

**Comment by twmb** [comment]
Oh, awesome.

FWIW, this is going into the next release (just committed it locally):
```diff
diff --git a/pkg/kgo/consumer_group.go b/pkg/kgo/consumer_group.go
index 5c9288a..d4edb68 100644
--- a/pkg/kgo/consumer_group.go
+++ b/pkg/kgo/consumer_group.go
@@ -1852,8 +1852,11 @@ func (g *groupConsumer) updateCommitted(
        if req.Generation != g.generation {
                return
        }
-       if g.uncommitted == nil || // just in case
-               len(req.Topics) != len(resp.Topics) { // bad kafka
+       if g.uncommitted == nil {
+               g.cfg.logger.Log(LogLevelWarn, "received an OffsetCommitResponse after our group session has ended, unable to handle this (were we kicked from the group?)")
+               return
+       }
+       if len(req.Topics) != len(resp.Topics) { // bad kafka
                g.cfg.logger.Log(LogLevelError, fmt.Sprintf("broker replied to our OffsetCommitRequest incorrectly! Num topics in request: %d, in reply: %d, we cannot handle this!", len(req.Topics), len(resp.Topics)), "group", g.cfg.group)
                return
        }
```

**Comment by Zach-Johnson** [comment]
Nice, that will make that condition much easier to understand when it happens!
