### ISSUE TITLE
unable to initialize sasl; broker: seed 1, err: EOF

### ISSUE THREAD

**Issue by vjakka-intel** [twmb/franz-go#258]
Hello,

I am using franzo-go package to connect to AWS MSK with IAM Role only.  I see below error in my log after 10 hours. But consumers are consuming message without any issue.

[INFO] metadata update triggered; why: opportunistic load during source backoff  
[ERROR] unable to initialize sasl; broker: seed 1, err: EOF
[INFO] metadata update triggered; why: opportunistic load during source backoff

Any suggestion on these error ?

Above INFO log, keep logging in log file. Any configuration parameter do i need to set to avoid above INFO log ? 
 I am using github.com/twmb/franz-go v1.10.0

**Comment by twmb** [comment]
Looks like the connection was closed during the SASL flow. This is a recoverable error, perhaps it shouldn't be at ERROR level, or I shouldn't log if it's just a simple connection close. I'm not sure why AWS would close the connection so quickly, but well, AWS MSK has been pretty problematic (you can see in other issues). I'm going to close this for now since this isn't an issue, but I'll adjust the error locally.
