### ISSUE TITLE
Is it ok to keep the producer connection open?

### ISSUE THREAD

**Issue by houmanka** [twmb/franz-go#296]
I have a workflow where I post the success event at the end to Kafka.
Currently it takes about 2 seconds to create connection to Kafka > Push message > close the connection. 

I need to push millions of messages into Kafka. I wonder if it would be ok for me to pass the connection into the Context at the very top of the workflow into my worker, and then I never close it and just keep it open and use it over and over again. 

Would I be leaking resources?

**Comment by twmb** [comment]
The request sounds a lot like #121, my response here is key: https://github.com/twmb/franz-go/issues/121#issuecomment-1055817531

What I think you could do:
* Use a custom Dialer
* Return a cached connection
* Tie the connection to the client in a separate user-managed type
* Once you close the client, put the connection back into the pool (if it has not been closed)

However, the last step is a bit problematic, because the client itself closes all open connections when the client is closed. You'd need to hook into the Close and disable it... which might leak resources in the end without some super involved hooks and checking (I'm honestly not sure).

If you can think of an API that solves my problems in #121, I'd be open to considering it. However, I don't think there's an easy way to just cache connections between clients. Instead, I'd cache the client itself (and use AddConsumeTopics / PurgeTopicsFromClient as needed).

**Comment by twmb** [comment]
I'm going to close this for now pre-emptively, but if you're working on an API idea, we can reopen. lmk if caching clients is a better alternative for you.
