### ISSUE TITLE
Applying offset to a consumer

### ISSUE THREAD

**Issue by bnkamalesh** [twmb/franz-go#323]
Hello,

I see there's a `kgo.NewOffset()` function provided, but I'm not able to figure out where to use this offset. The kgo.Client.SetOffsets accepts `EpochOffset`. Is there any way to let the client know, to start `from timestamp`? And I couldn't see any kgo.Opt to use the offset. And should we be setting offset per partition of the topic, or is that abstracted by the package?

**Comment by bnkamalesh** [comment]
Yet another self discovery after 1.5 days! 

```golang
offset := kgo.NewOffset().AfterMilli(time.Now().UnixMilli())
opt := kgo.ConsumeResetOffset(offset)
kgo.NewClient(opt)
```

Sigh, I always find it confusing to discover available configurations, when it's implemented using this option interface pattern (found in multiple packages).

**Comment by twmb** [comment]
Functional options in Go date back to the early Go days, back to when Dave Cheney wrote about it in [Functional Options for Friendly APIs](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis). Functional options allow more safety for projects in a few angles:

* I can ensure that you do not initialize an invalid option
* Zero initialization for fields is not always safe / a good default
* Most importantly to me: zero initialization for fields is not forward compatible. If you say `cfg := Cfg{Field1: "foo"}`, and I add `Field2`, then your code now initializes Field2 as 0 which may not be valid and, if I validate your provided options (which I do), means that you updating my library will now cause errors in your code

In pkg.go.dev, all configuration options are grouped under `Opt`, `ConsumerOpt`, `GroupOpt`, and `ProducerOpt`. I recommend skimming the APIs of the available options. If a struct's use (such as `Offset`) is not immediately clear, ctrl+f is a decent way to find which APIs accept the struct (such as `ConsumeResetOffset` as you found).

I accept and consider proposals and frequently implement them, even if they take a significant amount of time, because I care about the future of this project and about it being the best and most complete Kafka client in Go. If you have an idea for a better way of doing some aspects, please suggest a concrete API. I'm not really sure if there's a suggestion the passive aggressive ending to the above comment.

**Comment by bnkamalesh** [comment]
@twmb oh nope. Very grateful for this awesome & clean library. No intention of being passive or active aggressive! 😅 

It was just me thinking out loud, the fact that I have not yet learnt to navigate (meaning how do I easily find all option functions provided by the package) fn based options despite it being a very common and clean pattern for a long time.

**Comment by twmb** [comment]
No worries, tone is definitely hard to read sometimes 😅  I really do appreciate suggestions. Thank you for using this library to begin with, I wish the discoverability of it were a bit higher haha.

**Comment by bnkamalesh** [comment]
Haha I agree, usually I sprinkle smilies to offset this. But then, I've gotten feedback that it looks childish 😅

well, I'm back to my smiley ways 😎
