### ISSUE TITLE
Clarification on behaviour of PollRecords with kafka error

### ISSUE THREAD

**Issue by phil-schreiber** [twmb/franz-go#379]
Hey,
I have a question for my understanding. Is it intentional that PollRecords will not return after FetchMaxWait? 
In a recent kafka outage we saw that  group-consumers were apparently stuck on PollRecords. The client continued trying to read and write fetches:
```
2023-03-07T15:30:13.567+0100    info    system/logger.go:106    assigning partitions%!(EXTRA string=why, string=clearing assignment at end of group management session, string=how, kgo.assignHow=unassigning everything, string=input, kgo.fmtAssignment=)
2023-03-07T15:30:13.567+0100    error   system/logger.go:130    join and sync loop errored%!(EXTRA string=group, string=test-topic-v2, string=err, *fmt.wrapError=unable to dial: dial tcp 1.1.1.1: connect: network is unreachable, string=consecutive_errors, int=4, string=backoff, time.Duration=1.625541825s), error: <no error>
git.deepl.dev/deepl/dap/dap/ch_sink/system.(*zapLogger).Error
        /home/philipp/Work/dap/ch_sink/system/logger.go:130
git.deepl.dev/deepl/dap/dap/ch_sink/system.(*zapLogger).Errorf
        /home/philipp/Work/dap/ch_sink/system/logger.go:136
git.deepl.dev/deepl/dap/dap/ch_sink/system.(*zapLogger).Log
        /home/philipp/Work/dap/ch_sink/system/logger.go:76
github.com/twmb/franz-go/pkg/kgo.(*wrappedLogger).Log
        /home/philipp/go/pkg/mod/github.com/twmb/franz-go@v1.12.1/pkg/kgo/logger.go:123
github.com/twmb/franz-go/pkg/kgo.(*groupConsumer).manage
        /home/philipp/go/pkg/mod/github.com/twmb/franz-go@v1.12.1/pkg/kgo/consumer_group.go:390
2023-03-07T15:30:13.740+0100    debug   system/logger.go:96     opening connection to broker%!(EXTRA string=addr, string=10.10.118.14:9094, string=broker, string=seed 0)
```

When kafka becomes available again, this loop will continue, but still without returning from PollRecords, because the consumer is now not a member anymore.

As a bugfix I explored giving PollRecords a context with deadline. Issue here is: I will always run into this deadline with low traffic topics. My assumption was, that whatever happens, PollRecords would return after FetchMaxWait.

Would you have any best practice advice to handle a PollLoop in an fail-safe way?
Cheers and thanks for checking it out.

**Comment by twmb** [comment]
> but still without returning from PollRecords, because the consumer is now not a member anymore
The client should recover and rejoin the group. Is that not happening for you?

> My assumption was, that whatever happens, PollRecords would return after FetchMaxWait
Returning empty fetches was the original behavior of the client, but that was changed all the way back in [0.8.1](https://github.com/twmb/franz-go/blob/master/CHANGELOG.md#behavior-changes-3).

I saw some reports of confusion for why polling was returning with no records and no errors, _and_ if the client buffered fetches with no records and no errors, then throughput could be lower because the client would not fetch again until you drained something empty.

Errors that are internally retryable are stripped, and _more_ importantly for this case, a fetch request that fails is not bubbled back to the end user.

> I will always run into this deadline with low traffic topics

Is it possible to ignore a context.DeadlineExceeded error? e.g., `if fetches.Err0() == context.DeadlineExceeded` ... (preferably using `errors.Is`).

I'd also like to potentially start returning errors from polling if join & sync are failing. It's a bit awkward though, see https://github.com/twmb/franz-go/issues/321. I can't decide whether we'd want the error to be persistent across fetches, or just returned once (and refreshed for every group join fail & backoff). I'm leaning once. This would still be a behavior change to the errors that are returned while polling.

**Comment by phil-schreiber** [comment]
Hey Travis,

> The client should recover and rejoin the group. Is that not happening for you?
It didn't. My assumption is that this is due to us having BlockRebalanceOnPoll enabled ( as suggested for group and per partition consuming, which we do)

> Is it possible to ignore a context.DeadlineExceeded error? e.g., if fetches.Err0() == context.DeadlineExceeded ... (preferably using errors.Is).
That's exactly the way I went. It just feels a bit fishy to intentionally produce an error and then ignoring it. But it does solve all the problems we saw. The clients do recover now and resume consuming.

I do not have a strong opinion on returning errors from polling, but would also tend to say one error, similar to the client closed error would be much easier to handle.

Anyway, thanks a lot for the clarifications and taking the time.

Cheers
Philipp

**Comment by twmb** [comment]
> My assumption is that this is due to us having BlockRebalanceOnPoll enabled

Blocking only occurs at the moment a fetch is going to be returned -- it doesn't happen as soon as you enter poll. If the function is hanging because there are no fetches, rebalancing is not blocked. So, if things didn't rejoin, that's a bit suspicious to me still (unfortunately for me)

**Comment by phil-schreiber** [comment]
Cannot provide a minimal setup that reproduces the non-rejoining issue we observed.

I'm closing as we seem to be faring well with the deadline. 
Thanks again.

**Comment by twmb** [comment]
I'll start injecting group errors just once in the next release with this PR: https://github.com/twmb/franz-go/pull/387
