### ISSUE TITLE
[Question] REBALANCE_IN_PROGRESS error while committing offsets

### ISSUE THREAD

**Issue by alistairking** [twmb/franz-go#409]
Hey!

I'm almost certain this is about me doing something wrong, and not a bug with the library, but I'm hoping you might have an idea of _what_ it is that I'm doing wrong :)

So, I have a cooperative-sticky consumer that uses `BlockRebalanceOnPoll` and `DisableAutoCommit`, and then during the poll loop I do something like:
```go
	fs := k.PollRecords(ctx, maxFetch)
	defer k.AllowRebalance()
        // process records
	if err := k.CommitUncommittedOffsets(ctx); err != nil {
		if !errors.Is(err, context.Canceled) {
			log.Error().Err(err).Msg("failed to commit offsets")
		}
	}
```

When the group rebalances (e.g., adding a new topic-partition), I see from the rebalance event logs that only one consumer instance has had a partition added (as I'd expect), but then I see a bunch of these logs: https://github.com/twmb/franz-go/blob/1a59c2d62d0d0ebd115f4f507379189644972c1f/pkg/kgo/consumer_group.go#L1920 along with my `CommitUncommittedOffsets` call returning `kerr.RebalanceInProgress`.

I'm not sure why the consumers are failing to commit their offsets given that rebalances are blocked during the poll loop? (I don't see any evidence of consumer instances being evicted from the group due to timeouts.)

Any insight you might have would be much appreciated.

**Comment by twmb** [comment]
This has bugged me forever, too.

Notes from spelunking the Kafka source / how it can interact with the client:
* heartbeat sees RebalanceInProgress
* heartbeat revokes
* revoke finishes with nothing
* you Poll, since this is cooperative, there are still partitions with data
* rebalancing is "blocked"
* heartbeat loop finishes
* consumer enters join group
* you commit
* commit fails with RebalanceInProgress since the broker rejects commits between join group and sync group

* In eager mode consuming, you shouldn't get the error because there can be nothing to commit / you should be stuck polling
* In cooperative consuming, the blocking actually only blocks your callbacks -- the rebalance can still happen _up until_ you would lose _or_ be assigned partitions

I think the fix internally is to block the join request within the client, I can work on this later today I hope

**Comment by alistairking** [comment]
Huh, thanks. It definitely makes me feel better that I'm not the only one with this problem :)
Let me know if there is anything I can do to help.

**Comment by twmb** [comment]
If you could try this PR: https://github.com/twmb/franz-go/pull/410
before I test it further myself / merge it, that'd be good

**Comment by alistairking** [comment]
That was quick!
I don't _think_ I'll have time to test this today, but I can take it for a spin in 2-3 days from now

**Comment by alistairking** [comment]
Ok, I tried this out and I think that it's working. I deployed to a subset of consumer instances and I didn't see any of these errors from the members that I had upgraded.

**Comment by twmb** [comment]
I'm aiming to investigate one to three more things before releasing this, fwiw -- I don't think this is _that_ high priority to release ASAP, but it will be a patch release.

**Comment by alistairking** [comment]
No problem. Do you think #410 is in good enough shape for me to use that in the meantime?

**Comment by twmb** [comment]
I loop tested it for a long time, it should be

**Comment by twmb** [comment]
This is now pushed in v1.13.2

**Comment by alistairking** [comment]
Thanks a lot!
