### ISSUE TITLE
Question: Proper value for TransactionalID

### ISSUE THREAD

**Issue by nvx** [twmb/franz-go#416]
From what I can gather, TransactionalID should be unique for every running instance of a transaction-enabled producer. In the past it seems in some situations you would want this to be shared when consuming from a group (in this case it looks like it was really a prefix that would have the group/topic/partition information appended to it?), but as far as I can tell this is no longer the case.

Is there any reason for not just generating a UUID on startup and using that as the TransactionalID?

The examples for EOS consuming just take these in as flags without any real guidance for what to set them to, especially if running multiple instances.

**Comment by twmb** [comment]
You might want to give each hostname a unique txn ID, and then reuse that txnID for the client across restarts of your application. Or, if you're in k8s, you may want to come up with some scheme where a txnID is reused to fence some zombie process.

I've heard of people using uuid's for every client. That's a valid use case as well.

I think it mostly depends on what you're trying to get out of EOS, and I don't have the _best_ guidance on that since I've never personally used it for a production service.

**Comment by nvx** [comment]
Cheers for the advice, that makes sense.
