### ISSUE TITLE
Support search for offsets by timestamp

### ISSUE THREAD

**Issue by nmerkulov** [twmb/franz-go#46]
Hello there!

It is actually super useful to have this little thingy out of the box:
Get offset by given timestamp

It is supported by sarama, actually. But this lib suites our needs way better
So we'd glad to have it here =)

Link to OfffsetAPI https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetRequest

Link to corresponding KIP: https://cwiki.apache.org/confluence/display/KAFKA/KIP-33+-+Add+a+time+based+log+index

**Comment by twmb** [comment]
What workflow is desired here? All protocol requests are supported through the `kmsg` package.

Are you trying to group consume, and seek to a specific offset with the group itself? Or are you trying to consume partitions directly?

**Comment by twmb** [comment]
Or is this just trying to issue a list offsets request?

https://github.com/twmb/kcl/blob/3703d554bfba13d8664752120f4f5914bef299df/commands/misc/misc.go#L367-L402

^^ example of list offsets request. Although, if you use kmsg, be sure to use `kmsg.NewXyz` for every struct, and do not initialize structs directly. I should update kcl to be better example code -- initializing structs directly poses future compatibility problems as the protocol changes (due to not having RAII in Go)

**Comment by nmerkulov** [comment]
Yep, i list offsets request is exactly thing i wanted

i tried to figure out is it possible by myself, but didn't found it..

many thanx, will try it out!

and yeah, i want to implement something like "give me all events from %DATE%". But kafka works with offsets, not dates - hence first need to discover specific offset for that time period. And seems like ListOffset api allows to do so

**Comment by twmb** [comment]
Cool! So that would look like 
```go
req := kmsg.NewPtrListOffsetsRequest()
for _, topic := range topics {
    reqTopic := kmsg.NewListOffsetsRequestTopic()
    reqTopic.Topic = topic
    for _, partition := range partitions {
        reqPart := kmsg.NewListOffsetsRequestTopicPartition()
        reqPart.Partition = partition
        reqPart.Timestamp = <TIMESTAMP>
        reqTopic.Partitions = append(reqTopic.Partitions, reqPart)
    }
    req.Topics = append(req.Topics, reqTopic)
}
resp, err := client.RequestSharded(ctx, req)
````

It's a little tedious to define requests, but doing it that ^ way allows you to be safe from a new version introducing a new field (since `New` functions call `Default` before returning).

RequestSharded ensures to split the request appropriately, ... so this is definitely more low level / involved than sarama, but it avoids guessing any magic way to merge the response that may actually not be correct behavior.

**Comment by twmb** [comment]
Please let me know if the above doesn't solve this issue, thanks!

**Comment by twmb** [comment]
This now exists in the new kadm package:

https://github.com/twmb/franz-go/commit/e0d6ab19218824d3cf76a9a2041b68af9f247ae5#diff-c4337c0dc3a2717a1e64209fd7c350d9fae2e813137a955ddb542b174dd3f38bR244-R251

This is currently in a separate module, but the plan is to play with it for a short time and then merge to franz-go proper. If you get a chance to try this, please let me know what you think.
