### ISSUE TITLE
Not able to figure out how to get the offsets and partitions for produced records in a transaction

### ISSUE THREAD

**Issue by dennisharrison** [twmb/franz-go#550]
Hello, excellent library, was able to implement it very quickly, docs and examples were very easy to understand.

I'm trying to figure out how to get the partition and offset for records produced in a transaction, was excited to see ComittedOffsets() but it's always nil.

I'm obviously not doing this right, lol.

Is there something obvious I'm missing?

**Comment by twmb** [comment]
EOS transactions are meant to use GroupTransactSession, and the records that are committed are not exposed -- internally it's managed (committed and new transaction began all at once). This client doesn't really expose a way to manually manage transactions without using the GroupTransactSession, because transactions have so many odd edge cases that all the complexity is hidden internally.

For producing, there is no committed offset. Committed offsets are more for non-transactional group consumers.

What are you trying to do?

**Comment by dennisharrison** [comment]
I see, reading through the code now.

I'm trying to get the partition and offset a record was committed to - I guess I can use a non transactional sync to get this in the return (assumptions, sketchy of me, I know, lol)?

I want to get to something like:
https://github.com/twmb/franz-go/blob/master/examples/manual_committing/main.go#L70

For each record.

**Comment by twmb** [comment]
What's the code look like?
You can use Produce as well. The record's Offset and Partition fields (and a few others, which are documented) are updated before the records are passed to the callback.

**Comment by dennisharrison** [comment]
Would have to pseudocode the implementation to share it :(  It's simply an abstraction to handle configs and whatnot and expose pub/sub for a few event broker configurations.

I noticed the record sent to the callback has the partition and offset populated from Produce().  We're doing both sync and async.

So that's fantastic, we're almost done with the eventing lib/helper in this reference architecture project and this is one of the last requirements, we should see it in dev env next week.  

Very much looking forward to the first production service implementation using it - thanks!

P.S.
The admin stuff is rad :)
