### ISSUE TITLE
[Question] What is the minimum feasible solution with BlockRebalanceOnPoll to avoid duplicates?

### ISSUE THREAD

**Issue by ns-gzhang** [twmb/franz-go#587]
Hi @twmb I'm migrating an existing message routing app to the kgo driver. The app is pretty simple and consumes from a source topic and routes messages to the right partitions of the target topic for the next-phase app to consume from partitions as logs.
I'd like to have minimum changes to the code, yet to use the `BlockRebalanceOnPoll` option to avoid duplicates if possible. I saw you have nice per-partition consuming examples, but I'd like to avoid rewriting as the target producer will mix the source messages and there is no clean independent per source partition consumption. And I assume I could leave the OnPartitions-(...) as default, if I `AllowRebalance` after I flush the producer side and have clean commits (althouhh this has a performance concern - but I don't see a better alternative).
The number of partitions do not change. The K8s PODs belonging to the consumer group may change but are relatively stable. 

So the sketch of my code looks like the following (with questions in comments):
```
	opts := []kgo.Opt{
		kgo.SeedBrokers(brokers...),
		kgo.ConsumeTopics(c.Topic),
		kgo.ConsumerGroup(c.ConsumerGroup),
		kgo.ConsumeResetOffset(offset),
		kgo.BlockRebalanceOnPoll(),   // Q1: is it OK to leave OnPartitions-(...) callbacks as default?
		kgo.RebalanceTimeout(8 * time.Minute), // default 60s
		kgo.SessionTimeout(5 * time.Minute),
		kgo.DisableAutoCommit(),
		...
	},
	client, err = kgo.NewClient(opts...)
	rebalanceInterval := 5 * time.Second // Q2: not sure if this interval is too long, but too short would cause
                                             // performance concerns with flush before allowing rebalance?
	client.AllowRebalance()    // Q3: Is it necessary to allow rebalance before entering the fetch loop?
	nextAllowRebalanceTime := time.Now().Add(rebalanceInterval)
	for {
		fetches := client.PollFetches(c.ctx).   // Q4: do I need to have timeout so to AllowRebalance? Seems this could hang?
		if errs := fetches.Errors(); len(errs) > 0 {
			if c.ctx.Err() != nil { // canceled, exit loop
				break
			}
			continue  // Q5: Is there any data in fetches when it has errors for some partitions?
		}
		iter := fetches.RecordIter()
		for !iter.Done() {
			r := iter.Next()
			msgC <- r  // sent for routing processing
		}
		if time.Now().After(nextAllowRebalanceTime) { // only allow rebalance after an interval with clean flush and commit
			// flush producer of target here
			_ = client.CommitUncommittedOffsets(context.Background())

			client.AllowRebalance()
			nextAllowRebalanceTime = time.Now().Add(rebalanceInterval)
		}
	}
	client.CloseAllowingRebalance() // Q6: If a pod crashes without executing this, would that block rebalance for the consumer group?
```
Our Kafka brokers were old 2.4.0 (which is out of my control). Driver franz-go 1.13.6 (upgrading to 1.14.3). The current testing shows this seems not working as expected. Even after I removed the `BlockRebalanceOnPoll` option and used plain simple consuming, the code was stuck somehow (using the same consumer group).

Any insights and guidance are appreciated!

**Comment by ns-gzhang** [comment]
Add: It turned out that the initial rebalancing took ~5 minutes 30 seconds to finish, with 30 partitions and 8 pods, after we switched to RangeBalancer without BlockRebalanceOnPoll (and deleted the CG so it started clean). Is it normal and how we could improve it...?

**Comment by ns-gzhang** [comment]
In another environment, with same config, most pods in CrashLoopBackOff and restart before getting any data. Only one pod seemed to get data. The CG (one topic only) didn't get to a stable state.

**Comment by twmb** [comment]
Q1 in comment: yes it's ok to block rebalance on poll. `OnPartitions<*>` will be blocked after you poll, but will take priority before you try polling again: as soon as you allow rebalance, the OnPartitions callbacks can run.

Q2: I don't know what you're doing here / this rebalance interval context thing doesn't seem necessary, given the next two questions.

Q3: you do not need to allow rebalance before entering loop. Poll blocks rebalance, and rebalance blocks poll, and that's it. One or the other must occur before blocking occurs. For polling blocking rebalancing, specifically it is done here: https://github.com/twmb/franz-go/blob/95697530c665a05d5d62201289dd2c99884f3a2d/pkg/kgo/consumer.go#L429

Q4: Even more specifically, the fill closure doesn't block things the entire time. It's a lot of fancy locks/atomics, but in short: you do not need to have a timeout on your context. Rebalancing is only blocked the moment records are available and about to be returned to you.

Q5: There can be data in partitions. One broker may have returned an error, another may have returned records. Also (and importantly): even in the case of errors, you must allow rebalance before continuing.

Q6: no this does not block rebalancing for the group. However, since the client did not close cleanly, it did not leave the group. The partitions the client was consuming are not being consumed, and eventually (after the session timeout) the broker will notice the consumer has died and trigger a rebalance.

---

Second comment: did the consumer member leave the group beforehand? Rebalancing should not take this long, especially if you process records quickly. The slowest thing about rebalancing is how long you as a client user spend in OnPartitions callbacks or spend processing records.

---

If pods are crashing, this could cause rebalance to take a while, because of the rebalance timeout I mentioned.

**Comment by ns-gzhang** [comment]
Thanks @twmb . As I mentioned I simplified the code without using the BlockRebalanceOnPoll option. The code is almost like this (one of the simplest form):
```
	...
	client, err = kgo.NewClient(opts...)
        // check error here
	for {
		fetches := client.PollFetches(c.ctx)
		if errs := fetches.Errors(); len(errs) > 0 {
			if c.ctx.Err() != nil { // canceled, exit loop
				break
			}
			// continue  <= had this before but we didn't see error from log
		}
		iter := fetches.RecordIter()
		for !iter.Done() {
			r := iter.Next()
			msgC <- r  // sent for routing processing
		}
	}
	client.Close()
```
What could go wrong that could cause long initial rebalance and crashes (it had no data to process at all most time - but from time to time one pod got some data)? Thanks!

**Comment by twmb** [comment]
Do you use OnPartitionsRevoked or OnPartitionsLost? If yes, what's that look like?

**Comment by twmb** [comment]
Is sending what msgC blocked? The algorithm of rebalancing should not take that long -- especially with range.

**Comment by ns-gzhang** [comment]
Thank you Travis. The msgC channel itself has 5000 capacity, and from the log, it never got any data to process by the receiver. We were really puzzled. We will try to enable debug when we get a chance. For the time being, we switched back to the other driver under time pressure.

**Comment by twmb** [comment]
Thank you, please let me know. I'm very curious to see debug logs -- this should work (and is a reliable pattern I've seen and used). I hope you're able to switch back once we figure things out 😅

**Comment by twmb** [comment]
Closing for now as this is likely not a franz-go issue -- if you revisit this, we can reopen.
