### ISSUE TITLE
Commit behaviour when using kgo.DisableAutoCommit() 

### ISSUE THREAD

**Issue by kalbhor** [twmb/franz-go#598]
We have a use-case where we want to manually commit messages that are processed in a consumer group using `CommitOffsetsSync`. So as to disable auto-commit behavior we passed `kgo.DisableAutoCommit()` while initializing the client. We noticed that setting `kgo.DisableAutoCommit()` would commit the `head` as the final offset when we would close the consumer. After brief exploration we found that https://github.com/twmb/franz-go/blob/ae169a1f35c2ee6b130c4e520632b33e6c491e0b/pkg/kgo/consumer_group.go#L1814 would be called and it commits offsets till `head`. 

Our expectation when passing `kgo.DisableAutoCommit()` is that only manual commits are possible. I am curious to know why the library chooses to commit till `head` as the final commit when the consumer is closed.

**Comment by twmb** [comment]
Good find, I'll remove this.

**Comment by twmb** [comment]
Wait, coming back to this, I don't think this is a bug. I misread the issue originally -- I thought you were saying the client was committing automatically in LeaveGroup even though you had autocommit disabled, but that doesn't happen. With autocommit enabled, there is a goroutine that starts that commits head offsets (not dirty offsets) every 5s -- the difference between head and dirty is not relevant when disabling autocommit.

With autocommit disabled, the goroutine is not started. updateUncommited updates the head offset always, so that when you call UncommittedOffsets(), you have the latest offsets that you have polled available to commit.

When you close the consumer, OnPartitionsRevoked is called. With autocommit disabled, there is no commit here anywhere.

What's the confusion here?

**Comment by twmb** [comment]
Marked records are only relevant for `AutoCommitMarks`. Marking records is a no-op when you have disabled autocommit (and `MarkCommitRecords` documents that).

If you disable autocommit, all offsets you poll are always available / always what you receive when you query offsets (via `UncommittedOffsets()`, or `CommitUncommittedOffsets()`).

`CommitMarkedOffsets()` can be changed to be a no-op if autocommit is disabled, but this is just an added safety check -- the docs all currently dissuade you from using any mark APIs unless you've opted into `AutoCommitMarks`.

I'm not sure what the question is at this point -- do you need to switch methods? Is something else wrong here?

**Comment by kalbhor** [comment]
Your explanation is correct and ideally the library's user shouldn't be calling `Mark` related methods when autocommit is disabled as it is documented as a suggested usecase pattern in your docs as well. Maybe this is a more API border decision related issue since under the hood the library is considering `UncommittedOffsets` as `MarkedOffsets` when using `CommitMarkedOffsets()`. Uncommitted offsets and marked offsets are different in the case of auto-commit disabled. The library is assuming `CommitMarkedOffsets()` is only going to be used in the context of auto-commit. In that case maybe an error should be returned when using an abstraction like `CommitMarkedOffsets()` when auto-commit is disabled? Or it could be a no-op just like marking records is currently.

**Comment by twmb** [comment]
Sure.... I'll make the mark functions no-op.
