### ISSUE TITLE
Feature request: KIP-842

### ISSUE THREAD

**Issue by tmgstevens** [twmb/franz-go#621]
In [KIP-842](https://cwiki.apache.org/confluence/display/KAFKA/KIP-842%3A+Add+richer+group+offset+reset+mechanisms) the author requests the ability to have the following new parameters:

`auto.offset.reset.on.no.initial.offset` - to specify how offset reset is handled when a consumer is starting up. This can be set to:
- `none`
- `earliest_on_start`
- `latest_on_start`

`auto.offset.reset.on.invalid.offset`. - to specify how a consumer should behave if an invalid offset is suddenly received. This can be set to:
- `none` 
- `nearest`

We see users needing this quite often where they would usually like to consume from the beginning of a topic, unless there has been an issue, in which case they'd either like to default to latest or to nearest (which would avoid a reset back to the beginning).

As far as I can see this wouldn't need to be implemented upstream to be incorporated into Franz-go.

**Comment by twmb** [comment]
I remember reading this KIP and actually implemented `AfterMilli` in response to it, see here: https://github.com/twmb/franz-go/commit/e8e5c82a1668869a6c700889b29c06ecfead9c27
This was after reading the KIP and corresponding Kafka issue, specifically this comment: [KAFKA-12478](https://issues.apache.org/jira/browse/KAFKA-12478?focusedCommentId=17310106&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17310106).

w.r.t. `auto.offset.reset.on.no.initial.offset`, both `none` and `earliest_on_start` already exist. `none` exists in the form of NoResetOffset, and `ealiest_on_start` exists in the form of `AfterMilli`. AfterMilli basically says: consume any offset after this millisecond. Importantly, this also means that partitions added via CreatePartitions will by default have their first offset after that millisecond, so new partitions will consume from the start. I'm not sure of any purpose of `latest_on_start`, because that's just opting into some weird behavior of "I want to consume from some defined offset right now, but if new partitions are created, I want to skip the data".

`auto.offset.reset.on.invalid.offset` should have no purpose -- nearest should already by the default because of KIP-320 and/or KIP-392 (unless you use NoResetOffset). However, I am seeing one oversight between KIP-320 and KIP-392. Currently, KIP-320 dictates truncation detection by issuing OffsetForLeaderEpoch whenever the client receives FencedLeaderEpoch (KIP-320), or OffsetOutOfRange _when the client is consuming from a follower_ (KIP-392). However, if data loss occurs _on the leader_, before leadership is transferred to another broker / without a corresponding epoch bump on the broker, then the client currently resets following the current offset reset policy. KIP-320 does not mention the case of OOOR without a leader bump, and the old behavior of the client is to just reset following the offset reset policy. My guess is that OOOR due to data loss universally comes with a leadership transfer in Kafka -- there is no possibility of an offset rewind while keeping the same epoch and not transferring leadership.

OOOR can be returned in three scenarios, the first two of these which can be expected in the normal lifecycle of a client:
* Client is consuming before the beginning: with either Earliest or AfterMilli, the client will likely reset to the beginning (nearest).
* Client is consuming after the end, no broker data loss: This really is only possible if you start your client after the end, and if you're doing that, we currently trust whatever your offset reset policy is.
* Broker has a bug, causes data loss without bumping the epoch, and the client is now consuming after the end. This is the one case where adding "nearest" would be valuable. Per current Kafka semantics, the client is supposed to list and then follow the reset policy.

I think one way to move towards "nearest" is, in the case where you consume past the end, reset to `afterMilli(timestamp of last consumed record)`.

I'll create a patch that switches to resetting to after the millisecond of the last consumed record when OOOR is seen, and only if any records have been consumed. If OOOR is received on the _first_ fetch, the client will still assume that you manually set an offset that is out of range and that you want to follow your normal consume reset offset policy.

This patch will specifically address the scenario of an active client when the broker receives data loss but does not transfer leadership nor bump the epoch.

I think, given this patch, there is still no need for a true "nearest" option. To experience it, you would have to manually set your consume to start outside of range.

See #628, which follows the proposal in this comment.
