### ISSUE TITLE
Question on serde for Protobuf

### ISSUE THREAD

**Issue by kameshsampath** [twmb/franz-go#633]
/Question

I was looking at the example https://github.com/twmb/franz-go/blob/a6d10d4ad93528f7c2e8ed735a40bb1bd8a03c8a/examples/schema_registry/schema_registry.go#L65C2-L65C7,  is there any example for protobuf. 

Checking what could be right parameters for the same.

**Comment by kameshsampath** [comment]
I found the way to do it, 

**Registration**

```go
	rcl, err := sr.NewClient(sr.URLs(config.SchemaRegistry))
	if err != nil {
		log.Fatal(err)
	}

	sb, err := os.ReadFile(schemaFile)
	if err != nil {
		log.Fatal(err)
	}

	ss, err := rcl.CreateSchema(context.Background(), fmt.Sprintf("%s-value", config.DefaultProducerTopic()), sr.Schema{
		Type:   sr.TypeProtobuf,
		Schema: string(sb),
	})
	if err != nil {
		log.Fatal(err)
	}
```

** Using serde **

```go

       var protoMarshallFn = func(a any) ([]byte, error) {
	 return proto.Marshal(a.(proto.Message))
       }

      var protoUnMarshallFn = func(b []byte, a any) error {
	return proto.Unmarshal(b, a.(proto.Message))
      }
	var serde sr.Serde
	serde.Register(
		ss.SchemaID,
		&foo.MyRequest{}, // the proto message for the request
		sr.EncodeFn(protoMarshallFn),
		sr.DecodeFn(protoUnMarshallFn),
	)
```

**Comment by twmb** [comment]
For protobuf, make sure you use index, too

**Comment by kameshsampath** [comment]
Can you share more details on what you mean indexing here. Helps newbies like me 😁

**Comment by weeco** [comment]
In a single proto schema you can define multiple types. The index is a pointer to the type that you are serializing. If you only have a single type in that schema and you use that, you can use index = 0 for example. If you have multiple, nested types and you are using one of the inner types things get more complex. 

I think if you look at the `serde.DecodeIndex()` method you have an idea how this works backwards (for deserialization) at least. As far as I know this is not properly documented anywhere, because it's abstracted in the java reference client.

**Comment by twmb** [comment]
(Martin answered, closing)
