### ISSUE TITLE
add ability to provide own member id

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#734]
I'm already have service id (uuid) and want to stick with it id in consumer group. What do you think?

**Comment by twmb** [comment]
This is where you should be using instance IDs, rather than a standard member.

Are you intending to try to restart your application quickly, plug back in the prior member ID, and avoid any rebalance?
This really is exactly what instance IDs were introduced for, although they can be a bit cumbersome because it requires manual intervention to actually leave a group. Do instance IDs not suffice?

**Comment by vtolstov** [comment]
how i can use InstanceID ? does it possible to assign it from client opt ?

**Comment by twmb** [comment]
Yep, https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#InstanceID

Since InstanceID should solve this, I'll close the issue now.
