### ISSUE TITLE
Incorrect documentation regarding sarama partitioner compatibility SaramaCompatHasher

### ISSUE THREAD

**Issue by asg0451** [twmb/franz-go#764]
This suggestion is incorrect and does not compile: https://github.com/twmb/franz-go/blob/v1.17.0/pkg/kgo/partitioner.go#L529
Perhaps something like this was meant:

```
	hasher := fnv.New32a()
	 kgo.StickyKeyPartitioner(kgo.SaramaCompatHasher(func(bs []byte) uint32 {
			hasher.Reset()
			_, _ = hasher.Write(bs)
			return hasher.Sum32()
		}))

```

**Comment by twmb** [comment]
Feel free to submit a PR, this really was meant to be more pseudocode but I'm fine if we want to make this 100% correct.

**Comment by asg0451** [comment]
Gotcha. Can you confirm that what I wrote is correct? If so I'll submit a pr. thx

**Comment by asg0451** [comment]
(or i can just add `".. something like.."` in the comment ;)

**Comment by twmb** [comment]
Open to anything; if you're able to test the code and then mirror that into a doc line, I'll +1 a PR. Or, if you'd prefer "something like", I'll +1 that too.

**Comment by twmb** [comment]
Howdy, I'm actually looking into this myself, I see you added this code to cockroachdb/cockroach#126213 -- the correct code is

```go
hasher := fnv.New32a()
hasher.Write(bs)
return hasher.Sum32()
```

I just checked with `-gcflags '-m -m'` and this all inlines, so there is no new alloc for every partition call.

I'll push a PR to update the docs, please also update cockroachdb because the code as is is a race (the hasher could be called for two separate partitions at the same time, if you are producing concurrently).

**Comment by twmb** [comment]
Actually, looks like somebody already did this for me two days after my 1.17.0 release: https://github.com/twmb/franz-go/pull/747

I'll close this issue now, I'm going to be releasing 1.17.1 this weekend.

**Comment by asg0451** [comment]
Thanks for the find @twmb!
