### ISSUE TITLE
Fetch retry with COORDINATOR_NOT_AVAILABLE error never recovers

### ISSUE THREAD

**Issue by genzgd** [twmb/franz-go#816]
We had an issue connecting consumers to a standard Kafka cluster where the fetch returned a "COORDINATOR_NOT_AVAILABLE" error.  We continued to retry the fetch but the client never recovered.  We included `ForceMetadataRefresh` calls during the retry loop, but it didn't seem to help.  Note we are using the `KeepRetryableFetchErrors()` option and handling retries manually within our code.  The problem happened with several consumer applications connected to the same Kafka cluster, so presumably there was some glitch/coordinator change in the cluster.

When we completely restarted the applications with a new kgo.Client, the consumers worked correctly, so it seems clear that the Kafka cluster itself recovered.  In case of this error (which is considered "retryable"), do we nevertheless have to completely recreate the client?  Is there some other internal state we need to reset in the kgo.Client to get it to recognize the new coordinator?

**Comment by twmb** [comment]
You shouldn't have to recreate the client -- largely, the client was designed to never go down / never require restarts (barring txn problems, deliberately, since any auto-handling opens windows for duplicates).

The code block in the consumer that strips retryable errors from being returned OR keeps them for you is here: https://github.com/twmb/franz-go/blob/b77dd13e2bfaee7f5181df27b40ee4a4f6a73b09/pkg/kgo/source.go#L1085-L1098 -- and important to note is that there isn't much of a difference here. So, whether you're using `KeepRetryableFetchErrors()` or not shouldn't affect how the client recovers.

Are you able to recreate the problem you ran into? If so, do you have info or debug logs during the problem?

**Comment by genzgd** [comment]
Thanks -- yes, that was my impression too that the client should never need to be restarted.  Unfortunately there's no easy way to recreate the issue, as we've only had it occur in a couple of cases using our customer's Kafka clusters (at least two different customers).  At least two incidents involved the COORDINATOR_NOT_AVAILABLE error on a customer hosted redpanda cluster, so it's definitely possible it was a problem on their end.  The other incident involved a Amazon initiated rolling restart of an AWS MSK cluster.  I'll take a look at the `franz` code again.

If we do go ahead and recreate the client, are there potential side effects of that (assuming we wait for a successful Close)?

**Comment by genzgd** [comment]
Thanks as always for the feedback.  We should normally have info logs but at this point they have dropped off.  This particular customer seems to have an unstable Kafka configuration, so we may well see it again, in which case we should have at least info logs (we run many hundreds of copies of our application for our customers, so keeping debug logs on isn't currently practical).  I'll reopen with logs if that happens.
