### ISSUE TITLE
Consuming from Kafka with some wait time in between fetches

### ISSUE THREAD

**Issue by adriangomez24** [twmb/franz-go#828]
Hi!

I'm currently working on creating a library using franz-go to consume messages from Kafka. We have a special use case where we want enforce a variable amount of time between calls to `PollFetches()` which usually is anywhere between 5ms and 50ms. This is because we have 100s-1000s of consumers for our Kafka cluster and we don't want to overwhelm the cluster. 

When we initially created a minimal working example of consuming with franz-go with a 50ms delay, we found that the difference between when the message was published to kafka compared to when we received it was pretty high (~65-70ms).  We discovered that this is because `PollFetches` was just returning the records in [c.sourcesReadyForDraining](https://github.com/twmb/franz-go/blob/master/pkg/kgo/consumer.go#L473C26-L473C51) which was obtained in the past, thus the above metric is always lower bounded by the value set in time.Sleep(<time>). 

To circumvent this, we unlocked/locked the partition we were reading from before and after the call to `PollFetches` (respectively) using `ResumeFetchPartitions` and `PauseFetchPartitions` and found that this metric dropped down to ~25-30ms, meaning we were getting fresher data when consuming from Kafka. 

We were wondering if there are better/more performant ways to ensure that we read fresh data from Kafka using franz-go when including some delay in between calls to `PollFetches`. Any ideas/help would be greatly appreciated! In addition, I can also create a PR that achieves the desired behavior. 

Thank you for your time!  

Below is a minimal example of our logic based on the code in the ReadMe: 

```
// 2.) Consuming messages from a topic
for {
        time.Sleep(50*time.Millisecond) 
        cl.ResumeFetchPartitions(topicPartitionMap)
	fetches := cl.PollFetches(ctx)
        cl.PauseFetchPartitions(topicPartitionMap)
	if errs := fetches.Errors(); len(errs) > 0 {
		// All errors are retried internally when fetching, but non-retriable errors are
		// returned from polls so that users can notice and take action.
		panic(fmt.Sprint(errs))
	}

	// We can iterate through a record iterator...
	iter := fetches.RecordIter()
	for !iter.Done() {
		record := iter.Next()
		fmt.Println(string(record.Value), "from an iterator!")
	}
}
```

**Comment by adriangomez24** [comment]
I also found [this issue](https://github.com/twmb/franz-go/issues/489) and another takeaway from this is that all in-flight fetch requests will be killed which isn't desirable as well since we could get these fetches with a PollFetch() call with nil context.

**Comment by twmb** [comment]
I don't know how you can serve both goals of deliberately introducing latency in an effort to reduce load on the broker, but also reduce latency as much as possible. One thing you may consider doing is bumping up the FetchMinBytes, which causes the broker to wait longer before replying to clients -- this will both increase the size of batches returned to you, and should decrease load on the broker since clients will be fetching slightly less.

Closing for now but let me know if the idea doesn't work.

**Comment by adriangomez24** [comment]
@twmb Thanks for the response! 

We are actively undergoing a migration from segment's kafka-go to franz-go and even with the `ResumeFetchPartitions` and `PauseFetchPartitions`, we still find that franz-go is a bit slower than segment's kafka-go which natively supports this sleep feature with a `BatchReadInterval` config. This shouldn't be a big issue for us since we're planning on doing something similar to [here](https://www.uber.com/blog/kafka-async-queuing-with-consumer-proxy/) in the long term which will allow our proxy Kafka reader to use franz-go as is, but to resolve this issue currently, I think the proper solution would be something similar to what kafka-go does where there's a BatchReadInterval config and the background goroutine that does the fetching sleeps before getting the next fetch.

**Comment by twmb** [comment]
Where is `BatchReadInterval`? I'm not seeing it anywhere in https://pkg.go.dev/github.com/segmentio/kafka-go

I don't see `BatchReadInterval` in the kafka-go package, but if my understanding is correct, you want to ensure there's at least some latency before another `FetchRequest` is internally sent. In franz-go, fetches are only sent once the prior fetch that was buffered is drained.

If I'm understanding this correctly, I think you could also do something like this

```
timer := time.NewTimer(time.Nanosecond)
for {
    <-timer.C
    fs := cl.PollFetches(context.Background())
    timer.Reset(50*time.Millisecond)
    // do logic
}
```

This will ensure that you have at least 50ms between polls. This differs from your logic in that the sleep comes after polling rather than before. Putting the sleep before forces 50ms latency per poll _on top of_ any time taken to process the records, whereas putting the sleep after enforces a _maximum_ of 50ms extra latency, and 0 added latency if processing your records took long enough.
