### ISSUE TITLE
using  ProducerLinger(1 * time.Second) brings strange errors

### ISSUE THREAD

**Issue by vtolstov** [twmb/franz-go#84]
sometimes producing fails with : "records have timed out before they were able to be produced"

what does it mean?

**Comment by vtolstov** [comment]
so as i understand ProducerLinger not suitable to accumulate kafka records for specific duration

**Comment by twmb** [comment]
Linger does accumulate for a specific duration. You're hitting your record delivery timeout. Check your combination of these options. It really sounds like you're trying to do something automatic with multiple timing options that have close timeouts, which is bound to be a recipe for disaster. If you need utmost control, use ManualFlushing.

As an aside, this has been a lot of questions lately, and a lot of this behavior is I hope quite documented in the functions themselves. I'll be spending less time on these questions because there are so many, I recommend playing around with options, scanning the docs, and potentially peeking in the source to see where the option is used.

**Comment by vtolstov** [comment]
Yeah, sorry for bit issue traffic. RecordDeliveryTimeout was set in code that uses my package (that uses you package), so i don't saw it =(
