### ISSUE TITLE
error="unknown attributes on uncompressed message 8"

### ISSUE THREAD

**Issue by kevinconaway** [twmb/franz-go#90]
We are piloting this project out and are running in to this error when trying to consume from one of our brokers:

```
unknown attributes on uncompressed message 8
```

The error is being returned from `fetches.Errors()`

This particular broker cluster has the following settings:

```
version=2.2.1
inter.broker.protocol.version: "2.2"
log.message.format.version: "0.10.1"
```

We do *not* see the same issue on another broker cluster with the following settings:

```
version: 2.7.1
inter.broker.protocol.version: 2.7.1
log.message.format.version: "2.7"
```

I've tried passing different versions to the client via `kgo.MaxVersions` to no avail

Is there some other option that I should be setting here or is there any way to get more debug information about what is happening here?

**Comment by twmb** [comment]
I think this is a tiny bug in this client. The broker is returning LogAppendTime (bit 3) for a message, and the client is not expecting that. This is almost certainly an error introduced in a previous large refactoring, and was uncaught because the integration tests are on new Kafkas (message sets were removed in Kafka 0.11).

I can patch this quickly and tag a patch release.

**Comment by twmb** [comment]
If possible, can you try this commit? https://github.com/twmb/franz-go/commit/5fee169b75e708261b358db5c966084df5b29d47

If not, I can tag that directly, but if you can check that it fixes things before the patch release, that'd be great!

**Comment by kevinconaway** [comment]
Thanks.  

I was reading through the spec and noticed that `LogAppendTime` in bit 3 would cause the value to be `8`.  However _both_ of the clusters have `LogAppendTime` set as `message.timestamp.type`

**Comment by twmb** [comment]
Is the new cluster using records, vs. the old message set format?

**Comment by kevinconaway** [comment]
>If possible, can you try this commit? 5fee169

It looks like there is a compiler error here

>Is the new cluster using records, vs. the old message set format?

I'm sorry, I don't understand the question

**Comment by twmb** [comment]
> It looks like there is a compiler error here

That teaches me for thinking this was easy enough to not need to stash my other work, very sorry about that. I'll run the integration tests for the next commit just to be sure...

> I'm sorry, I don't understand the question

The other cluster settings you posted show `log.message.format.version: "2.7"`, which uses the "new" RecordBatch format, rather than the old MessageSet. The client isn't as sensitive on attributes for the newer format. Point is, if the new format has LogAppendTime, that'll be fine because the client doesn't choke as hard there.

**Comment by twmb** [comment]
https://github.com/twmb/franz-go/commit/6e639fb0844ee6c2cb385f15a9c70419cbe29844 compiles & passes (as well as the followup unrelated commit), if you could check.

**Comment by twmb** [comment]
I'll check back in an hour, if I don't hear back I'll go ahead and tag :)

**Comment by kevinconaway** [comment]
Just deployed this out to both clusters.  It is unfortunately still failing with the same error on the `2.2.1` cluster.

**Comment by kevinconaway** [comment]
[This](https://github.com/twmb/franz-go/commit/6e639fb0844ee6c2cb385f15a9c70419cbe29844#diff-c6763587c65f4655271050afcde2ba38165b48756f75072ab54f3093246efc61R1281) fails in this little [example](https://play.golang.org/p/L7U_aHfKIJ1) as well

My bit twiddling skills leave a lot to be desired but can't the 3rd bit for `LogAppendTime` be `0` _or_ `1`?  If so, I think this code is only checking if its `0`

**Comment by twmb** [comment]
Actually thinking about this further, per my understanding, bit 8 shouldnt
be set at all. Bits 1 and 2 correspond to compression in message set v0 and
v1, and then bit 3 corresponds to the timestamp type for v1. A value of 8
means bit 4 is set, which I know nothing about.

I’ll take a look to see what I find related to this. It’s possible my
understanding is slightly off, or worst case I can just relax this
validation since it isn’t providing much.

**Comment by kevinconaway** [comment]
>A value of 8 means bit 4 is set, which I know nothing about.

Per the [spec](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol):

>This byte holds metadata attributes about the message.
>
> The lowest 3 bits contain the compression codec used for the message.
>
> The fourth lowest bit represents the timestamp type. 0 stands for CreateTime and 1 stands for LogAppendTime. The producer should always set this bit to 0. (since 0.10.0)
>
> All other bits should be set to 0.

If thats the case, it seems like it is _only_ the fourth bit set so `0000 1000` -> 2^3 -> 8

**Comment by twmb** [comment]
Looking back at
https://kafka.apache.org/documentation/#messageset,it appears I
misunderstood their bits. I’m fairly sure I know the problem, and I can
patch this in 20. I read bits 0 to 2 as the first two bits, not the first
three, and that continued to make sense to me because Kafka never used more
than the first two bits for compression. Thanks for bringing this up, I can
patch this after lunch.

**Comment by twmb** [comment]
I very much hope this commit works: https://github.com/twmb/franz-go/commit/688d6fb91c9fb1f671b6538cd902e37c0b29eb35
Given the prior success rate, I'm expecting the worse, but please let me know.

**Comment by kevinconaway** [comment]
🤞 

Will take me ~30m to get it out

**Comment by kevinconaway** [comment]
Looks good!

**Comment by twmb** [comment]
Awesome, thank you! I've gone ahead and tagged this in v1.1.2. I'm going to close this for now but if anything else crops up please let me know!
