### ISSUE TITLE
Default heartbeat timeout is too high

### ISSUE THREAD

**Issue by AnatolyRugalev** [twmb/franz-go#92]
We experienced high latencies during standard Kafka failover process which happens on AWS MSK and we were able to track it down to the issue where hearbeat request hangs for too long with default library settings.

We figured that heartbeat request timeout is equal to `OverheadTimeout` option which is 20 seconds by default. Also, these requests are retriable which means that single heartbeat request which is very time-sensitive could stall consumption for some time.

We tested our hypothesis with this simple change where we limit total hearbeat execution time to `heartbeatInterval` and the situation improved drastically https://github.com/GetStream/franz-go/commit/07531b57571d1b6c7034a3394e7a9bd13032eeb0

For now we decided to lower overhead timeout and some other timings to achieve acceptable failover latency, but I think the library should have a reasonable limit for heartbeat request timeout and it shouldn't be higher than `heartbeatInterval`

**Comment by nmerkulov** [comment]
Hey there
Me and @AnatolyRugalev  working together =)

TBH i'm not 100% sure that spikes we're experiencing during kafka failover are always related to heartbeat. It was our main guess

Let me describe what we're experiencing

Besides the rest we measure 2 latency - `Producer latency` and `e2e latency` (i picked it up from [here](https://www.confluent.io/blog/configure-kafka-to-minimize-latency/))

Most of the reboots we see spikes in e2e latency. It doesn't happen every time, but we managed to repeat it often enough - one out of 3-4 broker reboots result in this. Problem with those reboots that we can't control schedule or at least pause AWS MSK maintenance, and sometimes aws notify us in a couple of days. So we want to make it as smooth as it possible.

Here are some numbers:
With default config one (or sometimes few) consumer group is stuck and don't consume anything for about minute and a half. It results in 1.5 minutes e2e latency spikes
After we decreased `Dialer` to 2 seconds, `RequestTimeoutOverhead` to 1 second `RetryTimeout` to 6 seconds we managed to make this number below 30 seconds. But essentially it remains the same - once broker is down - consumer 
group stops consume

Our staging setup is quite simple - 3 brokers, 1 topic with 3 partitions

We injected `debug` logger into client to grep some logs. And we figured, that group tried to connect to rebooted broker for about minute and a half and then happening `rebalance` and after that all stuck messages got consumed. Thats why we thought it might be related to rebalance. Because well, it is only 3 partitions. Of one node is down - it means that leader broker for this partition has changed


I can imagine alternative explanation as well, but i can't think how it can be mitigated

Lets imagine that during failover Node2 is down. And current consumer tries to fetch data from Node2. It waits until all timeouts are gone an then asks to update metadata. And to update metadata we actually have to make new request to one of a brokers. And this broker picked up randomly. And this FetchMetadataRequest hits Node2, which is down, and also waits until all timeouts are gone and then will retry with another broker. And then it comes to Node1, new metadata fetched and consumer/producer can start to make requests to survived brokers

If that sounds realistic then we an try to make sorta `weight` to broker and increase it every time request fails. And to fetch metadata we can get broker with least `weight`

**Comment by twmb** [comment]
I think there can be some timeout tuning in some places. Metadata could probably be lower, since if it fails, internally the only option is to retry anyway (rather than fail a group or something). I've also always wanted to make an improvement into which broken is chosen for metadata, but it's not the most obvious and has been lower priority.

Is it also possible that the producer side is stalled, because there are so many records backed up for the partitions that are currently not accepting writes? This could be checked with the `LeastBackupPartitioner`.

**Comment by twmb** [comment]
I've pushed a change that I hope helps address this issue: timeouts have been lowered from 1min to 30s (for heartbeat, actually only to 45s by default). More importantly, the connection overhead has been lowered to 10s. These two changes combined will make some failover a bit quicker. I see above that you've actually lowered the conn timeout overhead to 1s -- this is fairly aggressive imo and doesn't allow room for unexpected yet temporary latency. 5s may be a bit safer. 1s may be a bit aggressive: if MSK is replying to a fetch request but the reply takes just over 1s, the client would cut the request, and then if that keeps happening, you'll have no progress.

For the FetchMetadataRequest2 scenario where requests hit Node2, the metadata can hang for 10s, but after the request is cut due to timeout, the client will choose the next available broker. So, this should only result in 10s of hang.

As well, the client will now use a dedicated connection to join&sync. Both of these requests can take some time, so if a metadata request gets stacked on either of these, the metadata will be blocked. That should no longer be the case. I don't think this change actually helps this problem, but if it does, all the better.

I'm not sure I'd like to switch broker selection strategy at the moment (last+1), In the happy path, it shouldn't help much, and in the unhappy path, we're bouncing around which broker to choose anyway. When metadata is good and things are stable, metadata is only refreshed once every 5 minutes. When things are failing, we have to choose a different broker again anyway.

Did you get a chance to check out the `LeastBackupPartitioner`? It may be worth playing with, although it may lead to imbalance down the line.

**Comment by twmb** [comment]
I've tagged the above changes in v1.2.
